version: 2
updates:
  # NPM dependencies (React frontend)
  - package-ecosystem: "npm"
    directory: "/educhemlp.client"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "CHORE: "
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      all-deps:
        patterns:
          - "*"

  # Dockerfile updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "CHORE: "
      include: "scope"
    groups:
      all-docker:
        patterns:
          - "*"

  # .NET dependencies (backend)
  - package-ecosystem: "nuget"
    directory: "/EduchemLP.Server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "CHORE: "
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      all-nugets:
        patterns:
          - "*"
