version: '3.9'
services:
  db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./dbschema.sql:/docker-entrypoint-initdb.d/1-init.sql:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  db_data: